name: Windows-RDP

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/luutrucuatoi/admin5/main/w7.sh -OutFile w7.sh
    - name: Connect RDP CPU 2 Core - 7GB Ram - 256 SSD.
      run: cmd /c w7.sh
